name: CI

on:
  push:
    branches:
      - dh-moduleRef-siblings-195
  pull_request:
    branches:
      - dh-moduleRef-siblings-195

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: actions/checkout@v2
    - name: Run Gradle Build and Tests
      run: ./gradlew --no-daemon build
      working-directory: yang-lsp